spring:
  application:
    name: richmillionaire

  datasource:
    url: jdbc:postgresql://localhost:5432/richmillionaire
    username: postgres
    password: Ronaldo10
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
    access:
      default: NONE

server:
  port: 8080

jwt:
  secret: your-secret-key-change-this-in-production-minimum-256-bits-long
  expiration: 86400000

logging:
  level:
    com.richmillionaire: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

